// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectionStep = { id: string, collectorType: string, targetPlaceholder: string, label: string | null, options: Array<string> | null, initialValue: string | null, };
