// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchItem = { id: string, name: string, type: string, url: string | null, executable_path: string | null, args: string | null, cwd: string | null, env_variables: string | null, run_as_admin: boolean | null, in_terminal: boolean | null, is_dir: boolean | null, icon_url: string | null, shortcut: string | null, categoryId: string, columnId: string, };
